# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class EchargeReport < Formula
  desc "CLI tool for interacting with wallbox charging stations — fetch real-time status and generate charging reports."
  homepage "https://github.com/szilch/echarge-report"
  version "1.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/szilch/echarge-report/releases/download/v1.3.0/echarge-report_Darwin_x86_64.tar.gz"
      sha256 "cec94497568c0ef67d97b108d07cde32f3b61dd7bfd45d47c2227f6d4434eb0b"

      define_method(:install) do
        bin.install "echarge-report"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/szilch/echarge-report/releases/download/v1.3.0/echarge-report_Darwin_arm64.tar.gz"
      sha256 "ce819019c7d01ae599da238f25610b7ca4e5af50720ce018bd2965b978885848"

      define_method(:install) do
        bin.install "echarge-report"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/szilch/echarge-report/releases/download/v1.3.0/echarge-report_Linux_x86_64.tar.gz"
      sha256 "f417253da84ff1572abe7388d4a444ffc7da7a07daf341c172424d5c2b054fb6"
      define_method(:install) do
        bin.install "echarge-report"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/szilch/echarge-report/releases/download/v1.3.0/echarge-report_Linux_arm64.tar.gz"
      sha256 "8613eb60bfe74b1ce34ebe4aa19d57157838e710020e28e0cf768154bb8e1c73"
      define_method(:install) do
        bin.install "echarge-report"
      end
    end
  end

  test do
    system "#{bin}/echarge-report", "version"
  end
end
